[source.crates-io]
replace-with = "rsproxy-sparse"

[source.rsproxy-sparse]
registry = "sparse+https://rsproxy.cn/index/"

[http]
timeout = 120
low-speed-limit = 1
multiplexing = false

[net]
retry = 5
